### ISSUE TITLE
Elastic - Enable scolling

### ISSUE THREAD

**Issue by Jonn3y** [texxasrulez/account_details#1]
Hey,

first of all, nice work! 

I got an issue, using the elastic theme. Im not able to scroll down. 
So i can't see all the items. 

Greetings.

**Comment by meaz** [comment]
Yeah I have the same issue:
![roundcube](https://user-images.githubusercontent.com/13604424/73949647-fb198900-48fa-11ea-97cb-9116f7f8f0d7.png)

**Comment by texxasrulez** [comment]
I confirm issue. Give me a bit to fix.
Thank you for input.

**Comment by texxasrulez** [comment]
The latest [commit](https://github.com/texxasrulez/account_details/commit/ae219eb6157cb0e726f1fa1aa5dec82355135091) fixes this issue .... 

Many Thanks for your interest and have a great day ;-)

**Comment by meaz** [comment]
thanks a lot!

**Comment by texxasrulez** [comment]
You betcha @meaz

**Comment by texxasrulez** [comment]
Hey @meaz I have made this fully Elastic compatible now. Fixed Settings Icon to display a proper icon and what not. If you haven't downloaded latest commit, do me the honor and download it so you can check 'er out and let me know what you think. 
I appreciate the interest in my work ... ;-)

**Comment by meaz** [comment]
Hi @texxasrulez that looks perfect! Thanks!
