### ISSUE TITLE
Add davx5 as "Recommended clients"

### ISSUE THREAD

**Issue by meaz** [texxasrulez/account_details#2]
I would add Davx5 as a "recommended clients which support CardDAV protocol" as it is open-source and available on f-droid.

By the way, the link to Contact Editor (https://play.google.com/store/apps/details?id=org.dmfs.android.contacts&hl=en) is broken. And it is useless if you use davx5 as it syncs calendar and contacts.

**Comment by texxasrulez** [comment]
Since I have no time to actually test other clients to honestly recommend them, I am just removing Recommended clients all together. Thank you for your input.
