### ISSUE TITLE
Wrong Latest Version Online

### ISSUE THREAD

**Issue by meaz** [texxasrulez/account_details#3]
Hi,

I have:

`Latest Version Online: | Roundcube v1.4.2  is the latest version available for Download!`

whereas latest version is 1.4.3

**Comment by texxasrulez** [comment]
As per the Main Readme File you must make a cronjob for the updates .. .

Make an hourly cronjob with your web credentials as follows for Roundcube Version Checking:

curl https://api.github.com/repos/roundcube/roundcubemail/releases | grep tag_name | grep -o "[0-9].[0-9].[0-9]\{1,\}" | sort -n | tail -1 > /path_to_roundcube/plugins/account_details/rc_latest.txt
