### ISSUE TITLE
Compatiility with RC 1.6.0 ?

### ISSUE THREAD

**Issue by meaz** [texxasrulez/account_details#5]
Hi,

I've just switched to RC 1.6.0 and I see this in the logs:
`PHP Warning:  Undefined array key 1 in /var/www/roundcubemail-1.6.0/plugins/account_details/account_details.php on line 464`

Is that a compatibility issue?

**Comment by texxasrulez** [comment]
At the moment I do not have a server to host any of my projects. I am working on a solution so I can work on all my repos once again ...

**Comment by meaz** [comment]
FYI, it doesn't work at all with 1.6.1:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_quota() on null in roundcubemail-1.6.1/plugins/account_details/account_details.php:133
Stack trace:
#0 roundcubemail-1.6.1/program/include/rcmail_output_html.php(1484): account_details->infohtml()
#1 [internal function]: rcmail_output_html->xml_command()
#2 roundcubemail-1.6.1/program/include/rcmail_output_html.php(1322): preg_replace_callback()
#3 roundcubemail-1.6.1/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
#4 roundcubemail-1.6.1/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
#5 roundcubemail-1.6.1/plugins/account_details/account_details.php(52): rcmail_output_html->send()
#6 roundcubemail-1.6.1/program/lib/Roundcube/rcube_plugin_api.php(575): account_details->infostep()
#7 roundcubemail-1.6.1/program/include/rcmail.php(255): rcube_plugin_api->exec_action()
#8 roundcubemail-1.6.1/index.php(278): rcmail->action_handler()
#9 {main}
  thrown in roundcubemail-1.6.1/plugins/account_details/account_details.php on line 133

```

**Comment by elchusco** [comment]
Hi, I am facing exact same issue.

I could fix it by replacing in account_details.php line 132 :

```php
			$imap = $this->rc->imap;
```

by :

```php
			$imap = $this->rc->get_storage();
```

I was inspired by [jfcherng-roundcube/quota](https://github.com/jfcherng-roundcube/plugin-quota) plugin.

**Comment by uhlhosting** [comment]
> At the moment I do not have a server to host any of my projects. I am working on a solution so I can work on all my repos once again ...

I can provide you with dev server if needed.

**Comment by texxasrulez** [comment]
@uhlhosting thank you for the offer. The only reason I do not have a server is I am having some health issues and cannot work so I have no money to pay. I thank you for your offer but I also assume it would not be for free.

**Comment by uhlhosting** [comment]
@texxasrulez I can provide testing machine for free. Not big config but some kvm in my proxmox cluster can be managed for a few months.

**Comment by xkill** [comment]
> Hi, I am facing exact same issue.
> 
> I could fix it by replacing in account_details.php line 132 :
> 
> ```
> 			$imap = $this->rc->imap;
> ```
> 
> by :
> 
> ```
> 			$imap = $this->rc->get_storage();
> ```
> 
> I was inspired by [jfcherng-roundcube/quota](https://github.com/jfcherng-roundcube/plugin-quota) plugin.

Worked for me.

RoundCube 1.6.1 and PHP 8.1

**Comment by texxasrulez** [comment]
Hey @uhlhosting, I truly appreciate your offer. You are too kind.  I cannot in good conscience take something that you are trying to make a living at but I can spread the word of your kindness. I am currently able to piggyback off a friends server at the moment and will start fixing stuff ASAP. Thank you again and have a great day ...

**Comment by texxasrulez** [comment]
I have a little server again and am starting to work on some of these repos that need updating for current PHP. I am sure it will take a while to get everything up to date since it has been over 2 years since I have had a server and many things have changed. I am uploading a working, albeit not everything, version so I can have more eyes giving me errors to fix it as needed. Thank you all ...

**Comment by texxasrulez** [comment]
This issue should be fixed with latest release
